### ISSUE TITLE
Relation

### ISSUE THREAD

**Issue by ComMouse** [dyweb/bmFu#13]
Do we need to deal with relation tables & join staff? If yes, we need to extend the model to support it. @at15 @swaylq @arrowrowe @xsfour

**Comment by at15** [comment]
I think we already have a lot of things in tongqu's todolist, and most of them don't need relation very much. But we can consider just implement some of the relations, like `hasMany`. And the core for bmfu is not stable yet, and we haven't test it in production environment. It's better to keep the core clean and simple now. BTW: we should use trait or other things instead of extending `Model` class  directly, it already has 500 lines ( And you add some string helper function into it @arrowrowe, you may separate these util functions somewhere else). No one like a big class, especially when it has some bug ... maybe we should take look at `symfony` or other php `framework` or `orm`. I think laravel's is a good example, but not good enough....

**Comment by ComMouse** [comment]
Laravel's Eloquent has 28KB, and it's not a good example too...

**Comment by at15** [comment]
@ComMouse yeah..... Maybe we should change to other language now .....

**Comment by arrowrowe** [comment]
:sob:

**Comment by at15** [comment]
lol, almost one year and I am still single
