### ISSUE TITLE
Collection

### ISSUE THREAD

**Issue by ComMouse** [dyweb/bmFu#14]
Do we need to realize it? If yes, then
- Just use to iterate the objects (array wrapper)?
- Also used in ``insert_batch``, ``update_batch``?

Needs further discussion.

**Comment by at15** [comment]
I think we need collection in these circumstances

1. Read a lot of data. But this is included in `Model`'s pagination  feature.
2. Update a lot of data. 

(Some times query builder is easier ... `$this->db->where('user_name','jack')->where('status',1)->update('notifications',array('status'=>2))`)

3. Insert a lot data.  When use laravel I just new a lot of Model and save them, or use `Notification:create()` in a for loop.

Insert is not a big problem, because read and update is used much more. @arrowrowe @xsfour @swaylq  your suggestion?

**Comment by ComMouse** [comment]
Cause it cannot do more help obviously, I think it can be delayed..

**Comment by at15** [comment]
yeap, add a do it later label
